# Generated by Django 2.1.2 on 2018-10-02 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='published_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
